fix: refactored analytics to provide linting and testing results; feat: refactored to getting semver and releasing in main

diff --git a/.github/workflows/analysis.yml b/.github/workflows/analysis.yml
--- a/.github/workflows/analysis.yml
+++ b/.github/workflows/analysis.yml
@@ -14,48 +14,63 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
+  conventional-commit-check:
+    name: conventional-commit-check
+    if: ${{ ! github.event.pull_request.draft }}
+    runs-on: ubuntu-latest  # Runs on the latest version of Ubuntu
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4  # Checks out the code for the current pull request
+        with:
+          fetch-depth: 0
+
+      - name: Check commit messages
+        run: |
+          set -eux
+          #git fetch origin ${{ needs.vars.outputs.commit_ref }}
+          git log origin/${{ github.event.pull_request.base.ref }}..HEAD --pretty=format:%s | grep -qE "^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert|WIP|BREAKING CHANGE): " || {
+            echo "Aborting: Commit message does not follow conventional commits format.";
+            echo "Message: $(git log origin/${{ github.event.pull_request.base.ref }}..HEAD --pretty=format:%s)";
+            exit 1
+          }
+  lint:
+    name: lint
+    if: ${{ ! github.event.pull_request.draft }}
+    runs-on: ubuntu-latest  # Runs on the latest version of Ubuntu
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4  # Checks out the code from the repository
+
+      - name: Set up Node.js
+      - uses: actions/setup-node@v4
+        with:
+          node-version: '20.x'
+
+      - name: Install dependencies
+        run: npm install  # Installs project dependencies
+
+      - name: Lint code
+        run: npx eslint . --config .eslintrc.cjs  # Run ESLint with the specified config
+      
   tests:
     name: Tests
     if: ${{ ! github.event.pull_request.draft }}
     runs-on: ubuntu-22.04
     timeout-minutes: 5
-    services:
-      postgres:
-        image: postgres
-        env:
-          POSTGRES_PASSWORD: postgres
-        options: >-
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-        ports:
-          - 5432:5432
-    strategy:
-      matrix:
-        dir: [backend, frontend]
-        include:
-          - dir: backend
-            token: SONAR_TOKEN_BACKEND
-          - dir: frontend
-            token: SONAR_TOKEN_FRONTEND
     steps:
-      - uses: bcgov-nr/action-test-and-analyse@v1.2.1
+      - name: Checkout code
+        uses: actions/checkout@v4  # Checks out the code from the repository
+
+      - name: Set up Node.js
+      - uses: actions/setup-node@v4
         with:
-          commands: |
-            npm ci
-            npm run test:cov
-          dir: ${{ matrix.dir }}
-          node_version: "22"
-          sonar_args: >
-            -Dsonar.exclusions=**/coverage/**,**/node_modules/**,**/*spec.ts
-            -Dsonar.organization=bcgov-sonarcloud
-            -Dsonar.projectKey=quickstart-openshift_${{ matrix.dir }}
-            -Dsonar.sources=src
-            -Dsonar.tests.inclusions=**/*spec.ts
-            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
-          sonar_token: ${{ secrets[matrix.token] }}
-          triggers: ('${{ matrix.dir }}/')
+          node-version: '20.x'
+
+      - name: Install dependencies
+        run: npm install  # Installs project dependencies
+      
+      - name: Run tests
+        run: npm test # Step 4: Run tests using the specified Node.js version.
 
   # https://github.com/marketplace/actions/aqua-security-trivy
   trivy:
@@ -82,7 +97,7 @@ jobs:
 
   results:
     name: Analysis Results
-    needs: [tests, trivy]
+    needs: [conventional-commit-check, lint ,tests, trivy]
     if: always()
     runs-on: ubuntu-22.04
     steps:
