fix: iterating

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -6,6 +6,9 @@ on:
       - main
   release:
     types: [created]
+  pull_request:
+    branches:
+      - main
 
 jobs:
   lint:
@@ -26,9 +29,24 @@ jobs:
       - name: Run linting
         run: npm run lint # Ensure you have a lint script in your package.json
 
-  versioning:
+  commit-check:
     runs-on: ubuntu-latest
     needs: lint
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Check commit messages
+        run: |
+          git fetch origin ${{ github.event.pull_request.base.ref }}  # Fetch the base branch
+          git log origin/${{ github.event.pull_request.base.ref }}..HEAD --pretty=format:%s | grep -qE "^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert|WIP|BREAKING CHANGE): " || {
+            echo "Aborting: Commit message does not follow conventional commits format." && exit 1
+          }
+
+  versioning:
+    runs-on: ubuntu-latest
+    needs: commit-check
 
     steps:
       - name: Checkout code
