fix: iterating

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -42,7 +42,9 @@ jobs:
         run: |
           git fetch origin ${{ github.event.pull_request.base.ref }}
           git log origin/${{ github.event.pull_request.base.ref }}..HEAD --pretty=format:%s | grep -qE "^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert|WIP|BREAKING CHANGE): " || {
-            echo "Aborting: Commit message does not follow conventional commits format." && exit 1
+            echo "Aborting: Commit message does not follow conventional commits format.";
+            echo "Message: $(git log origin/${{ github.event.pull_request.base.ref }}..HEAD --pretty=format:%s)";
+            exit 1
           }
 
   versioning:
